name: baseX
description: BaseX Running With Flutter >=3.38.7

publish_to: "none"

version: 0.4.0

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.38.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.9.1
  huawei_hmsavailability: ^6.12.0+300
  gms_check: ^1.0.4
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  get: ^4.7.3
  flutter_local_notifications: ^20.0.0
  path_provider: ^2.1.5
  android_id: ^0.5.1
  cached_network_image: ^3.4.1
  ios_utsname_ext: ^2.3.0
  map_launcher: ^4.4.3
  flutter_svg: ^2.0.16
  flutter_facebook_auth: ^7.1.5
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
